### ISSUE TITLE
心得

### ISSUE THREAD

**Issue by lawrencepiao** [lawrencepiao/work-matome#2]
乱码基本上是没有条成中文和英文
修改文件要先把原来的存档

出勤表-hr-master 表，数据放进去不太会变更
                 业务表，经常会用，更新，每天出勤，缺勤，erp系统中的人事，小的部分出勤管理

成绩表，学校中的业务，如上

简历的模版放桌面上随时更新

**Comment by lawrencepiao** [comment]
首先我今天要做的是如何从命令行启动mysql
现在我打开command line,输入mysql，提示不是内部命令
然后、查找mysql安装路径。
这里有一大堆mysql, mysql router,mysql workbench,mysql server,mysql shell
我就选server了，然后去环境变量中改path，没效果

后来不了了之，原来我已经开了服务了，方法在
https://blog.csdn.net/sinat_32034679/article/details/69223234

就是从win plus r输入 services.msc，就可以看见了

**Comment by lawrencepiao** [comment]
遇到好多问题啊
比如mysql unicode中，大不了等号，从另一个界面打出等号再复制过来是方块。。。
解决方法用mysql不带unicode的命令行，然后就能显示出来了

**Comment by lawrencepiao** [comment]
mysql model中，一些缩略语意思
PK：primary key 主键

NN：not null 非空

UQ：unique 唯一索引

BIN：binary 二进制数据(比text更大的二进制数据)

UN：unsigned 无符号     整数（非负数）

ZF：zero fill 填充0 例如字段内容是1 int(4), 则内容显示为0001 

AI：auto increment 自增

G：generated column 生成列

在mysql查询语句中加\g、\G的意思：

\g  的作用是分号和在sql语句中写“；”是等效的 
\G  的作用是将查到的结构旋转90度变成纵向（换行打印）
--------------------- 
作者：ZeroBz 
来源：CSDN 
原文：https://blog.csdn.net/ZeroBz/article/details/79136926 
版权声明：本文为博主原创文章，转载请附上博文链接！

**Comment by lawrencepiao** [comment]
a黑盒测试---不看代码，只参照样式书，按照客户的要求，不管怎么样都能实现
正常系测试，有画面的都跑一遍，按流程，各种都能d登,
0条时候，什么都不输
1条
多条
边界值，年龄字段，最小值，最大，凡是涉及到项目，
这些都要跑到
经验者，输一条就能测到很多
最终结果，客户只关心是否全覆盖到了
入力条件，预想结果，执行者，执行日期，执行结果ok,ng
异常系测试，故意输入错误，出现的错误不能当机
b白盒测试---看代码

**Comment by lawrencepiao** [comment]
mysql启动的命令
mysql -u root -p
https://blog.csdn.net/qq_34178998/article/details/76578233

**Comment by lawrencepiao** [comment]
今天遇到的问题
1。mac电脑33的电池就开不了机
2。没休息好累
3。一台屏幕效率太低--这点其实可以解决，我有ipad,
4。发现自己启动时间太慢，跟血清素低有关系
5。今晚按照上面的链接做一下，做到23-00

**Comment by lawrencepiao** [comment]
eclipse中" cannot be resolved to a type"的解决办法
https://blog.csdn.net/qq_32575047/article/details/54848932

今天学会了在eclipse中建立2级包，就是点下拉箭头选hierachy

https://blog.csdn.net/believejava/article/details/39099709

**Comment by lawrencepiao** [comment]
遇到的问题，
今天要在eclipse中创建包里的子包，但是不管怎么按都是显示都是平级，甚至即使瞬间以子级的关系出现在了母包下也会变回平级，参照网上是下拉三角中的project presentation,改成hierarchical,但是还是没用，我发现原来下面几个选项里还有个package presentation,于是也改成hierarchical了，这下终于弄好子包了

**Comment by lawrencepiao** [comment]
又建立不子包
这次解决方法是，一定要先在母包里建立个类，然后才能在视图上建立出上下关系的子包

**Comment by lawrencepiao** [comment]
https://www.jianshu.com/p/f7ef551be77d

**Comment by lawrencepiao** [comment]
还剩5个问题没有解决
先看第一个
1。。Classpath entry D:/Tools/DB/mysql-connector-java-8.0.13/mysql-connector-java-8.0.13.jar will not be exported or published. Runtime ClassNotFoundExceptions may result.  	网上学生成绩管理系统		P/网上学生成绩管理系统	Classpath Dependency Validator Message

三.去除eclipse中jar包关联性警告

　　我们在开发过程中会接触到两种环境，一是开发环境(对应eclipse中的类路径)，二是运行环境(对应应用服务器中的类路径)。这时两个环境中jar包的关系就比较复杂了。这时处理jar包间的关系的总体原则是要保持这两个环境中jar包的版本一致或者兼容。 　　 
　　在项目WEB-INF\lib目录中的jar包是两个环境中共用的部分。这部分jar包要求不能和两个环境中的jar包有冲突，也就是说lib目录下的jar包是和两个环境中的jar包互补的。而两个环境中的jar包原则上应该是相同的或者兼容的。 
　　例如在eclipse下开发javaEE项目，我们会用到javaEE相关的jar包javaEE.jar,这时的需求是开发环境的需求。但在应用服务器环境中就不需要这个jar,因为应用服务器中会有相关的javaEE的jar包。这时如果我们将项目发布到应用服务器环境中，就会发生jar包冲突的情况。可是我们在开发时还要用这个包，发布时还不能发布到应用服务器中，这怎么办呢？ 解决的办法如下： 
--------------------- 
右键quick fix，


https://blog.csdn.net/qq_39501726/article/details/81560999
zhepian shi jiejue

**Comment by lawrencepiao** [comment]
1.欠钱互相记着的事例，要主动
2.在网吧装了jdk和eclipse，后者无法启动原因在于下载了how2j的老版本jdk，maybe
3.研修报告写法，进度非常重要

**Comment by lawrencepiao** [comment]
研修报告6个点
作业内容
开始时间
预计完了时间
进度
问题点
其他

**Comment by lawrencepiao** [comment]
13-05 enter
尝试打开tomcat localhost8080
失败
显示
HTTPステータス 404 - Not Found
Type ステータスレポート

メッセージ /

説明 The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/8.5.37

从文件夹bin/startup.bat再输入localhost；8080
能打开

Port 80 required by Tomcat v8.5 Server at localhost is already in use. The server may already be running in another process, or a system process may be using the port. To start this server you will need to stop the other process or change the port number(s).


改了端口后出现页面但是

HTTPステータス 404 - Not Found

--------------------------------------------------------------------------------

Type ステータスレポート

メッセージ /%E7%BD%91%E4%B8%8A%E5%AD%A6%E7%94%9F%E6%88%90%E7%BB%A9%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F/

説明 The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

--------------------------------------------------------------------------------

Apache Tomcat/8.5.37



这个错就是Tomcat没有找到你的项目，在新建服务的时候需要修改Tomcat的安装路径和部署路径，默认如下；



我们要修改成自己本地的安装路径和Tomcat默认的执行路径，可以在Tomcat的sever.xml文件中查看（sever.xml路径：Tomcat安装路径/conf/sevet.xml），打开sever.xml文件，看到appBase="webapps"；


--------------------- 
打开sever.xml

发现的确appBase-webapps

所以服务要修改为本地的安装路径和Deploy path或者修改sever.xml的appBase，反正sever.xml的Deploy path和appBase要一致。


然后我双击eclipse的server，发现server location无法编辑是灰色
于是我google

若要更改，則把tomcat下的所有項目移除。并右击，clean...之后方可設置。。。启动后将又变为黑色

如何把tomcat下的所有项目移除，右键add and remove，clean完了，再启动，的确变为可编辑状态了

可是仍然不行，并且又自动变成原来的了
现在


这次我改动的server.xml里面appBase改成,wtpwebapps



HTTPステータス 404 - Not Found

--------------------------------------------------------------------------------

Type ステータスレポート

メッセージ /%E7%BD%91%E4%B8%8A%E5%AD%A6%E7%94%9F%E6%88%90%E7%BB%A9%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F/

説明 The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.



还是这个错误

找到一篇文章是404错误总结，照着方法进行排查

步骤 1 : 404问题 
404表示File Not Found， 文件不存在错误。
通过学员反映，出现比较多的问题是页面报404错误，因此除了前面的 Tomcat 问题排查 之外，又专门做了这么一个404问题排查的文章，提供问题分析的思路和对策。
 
步骤 2 : 正确的端口号 
出现404错误证明，TOMCAT是启动成功了的。 但是在一台计算机上，可以启动多个端口号不一样的TOMCAT, 所以请确保自己访问的是正确的那个端口号，别自己启动的是8080端口号的TOMCAT,但是访问的地址却用的是80端口（默认），这样肯定会出现404错误的。



 
步骤 3 : 环境变量 
假设有两个Tomcat A和 B，自己分明运行的是B 下的startup.bat, 但是启动的却是A，为什么会这样呢？ 这就是环境变量在作祟了。
在环境变量中有两个属性：分别是CATALINA_HOME和CATALNIA_BASE，如果这个值指向的是A，那么即便运行的是B下的startup.bat, 真正启动的还会是A。
解决办法： 删除掉这个环境变量，或者使用移除了环境变量影响的纯净版 Tomcat。
 
步骤 4 : 确定Web应用是否成功启动 
虽然Tomcat启动成功了，但是对应的Web应用启动失败，依然会导致404错误。
怎么判断Web应用成功与失败呢？ 倘若Web引用启动失败，那么就一定会在Tomcat的logs目录下的 localhost.当前日期.log 里留下错误信息。
打开这个文件，检查对应的Web应用是否启动过程中报错了。 也许是web.xml多写了一个标签结束，也许是对应的servlet类找不到。
确定Web应用是否成功启动
 
步骤 5 : webapps下的ROOT目录 
有的时候，在server.xml 中配置的<context 是以“/"为开始路径的，与此同时，在webapps目录下还存在一个ROOT目录，这个ROOT目录其实也是告诉tomcat，以“/” 为开始路径，那么这样就发生冲突了，Tomcat只能二选一，通常情况下都会选择ROOT目录，那么在server.xml中配置的就<context 就无法启动了，导致访问对应的资源提示404错误。


 步骤 6 : 访问地址的时候是否加了web应用的名称 
这个也是常犯的错误，加入部署的时候，指定了路径，比如：
<Context path="/j2ee" docBase="e:\\project\\j2ee\\web" debug="0" reloadable="false" />
那么访问的时候，要记得加上j2ee，像这样：
http://127.0.0.1:8080/j2ee/hello



 步骤 7 : 是否访问对资源了 
这种错误也常见，你写的文件是 hello.html， 但是访问的是 holle.html，自然会提示404啦



 步骤 8 : 不能访问WEB-INF目录下的资源 

从安全角度触发，TOMCAT不允许访问WEB-INF目录下的HTML,JSP文件。 所以如果你的资源文件放在WEB-INF下，也会提示404错误
--------------------- 


HTTPステータス 404 - Not Found

--------------------------------------------------------------------------------

Type ステータスレポート

メッセージ /MyJavawebProject/

説明 The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

--------------------------------------------------------------------------------

step1
下好了项目，改文件中配置，改成tomcat 8.5和java1.8
zai import

发布后错误404，然后我开始改server.xml里的appbase，让他和eclipse里的一致


Classpath entry C:/Users/kisuser/Downloads/网上学生成绩管理系统/项目其他文件/jar包/taglibs-standard-compat-1.2.1.


HTTPステータス 404 - Not Found
Type ステータスレポート

メッセージ /

説明 The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.


终于运行起来了，感觉我多做了几步，一是在setting里加了tomcat的runtime-tomcat8.5
二是stackoverflow里，关于一个错误，
java.io.FileNotFoundException: the system cannot find the file specified
https://stackoverflow.com/questions/19871955/java-io-filenotfoundexception-the-system-cannot-find-the-file-specified

java.lang.NullPointerException这个叫空指针异常
你创建一个类，没有赋值


又有人说是jsp页面写得不好，所以现在改
Invalid location of tag (tr).
tr表示一行，把h2写进里面，还是warning
于是我pass



init [SQL驱动程序初始化失败！]
com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:921)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:885)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3421)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1247)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2775)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.util.DBconn.init(DBconn.java:16)
	at com.dao.StuDaoImpl.mgrlogin(StuDaoImpl.java:45)
	at com.servlet.MgrLoginServlet.doPost(MgrLoginServlet.java:32)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.filter.EncodingFilter.doFilter(EncodingFilter.java:23)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
1 31, 2019 5:48:51 午後 org.apache.catalina.core.StandardWrapperValve invoke
重大: サーブレット [com.servlet.MgrLoginServlet] のServlet.service()が例外を投げました
java.lang.NullPointerException
	at com.util.DBconn.selectSql(DBconn.java:36)
	at com.dao.StuDaoImpl.mgrlogin(StuDaoImpl.java:46)
	at com.servlet.MgrLoginServlet.doPost(MgrLoginServlet.java:32)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.filter.EncodingFilter.doFilter(EncodingFilter.java:23)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lawrencepiao** [comment]
com.mysql.jdbc.exceptions.MySQLNonTransientConnectionException: Client does not support authentication protocol requested by server; consider upgrading MySQL client
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:921)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2985)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:885)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3421)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1247)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2775)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1555)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:285)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.util.DBconn.init(DBconn.java:16)
	at com.dao.StuDaoImpl.stulogin(StuDaoImpl.java:28)
	at com.servlet.StuLoginServlet.doPost(StuLoginServlet.java:32)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.filter.EncodingFilter.doFilter(EncodingFilter.java:23)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2 01, 2019 2:08:37 午後 org.apache.catalina.core.StandardWrapperValve invoke
重大: サーブレット [com.servlet.StuLoginServlet] のServlet.service()が例外を投げました
java.lang.NullPointerException
	at com.util.DBconn.selectSql(DBconn.java:36)
	at com.dao.StuDaoImpl.stulogin(StuDaoImpl.java:29)
	at com.servlet.StuLoginServlet.doPost(StuLoginServlet.java:32)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.filter.EncodingFilter.doFilter(EncodingFilter.java:23)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

init [SQL驱动程序初始化失败！]

**Comment by lawrencepiao** [comment]
sap logon (gui)

right is the server

remember the reset login password
if forgot, try
command code su01 install and id confirmed(when password wrong and locked)etting

ro-ru s

push the pencil icon ,press logon data

/n (back to start point)

for the data structure, must turn back and toward to new function

/ofb50

/o  (open a new window) maximum 6 windows

/nse38 most 90% coding is beyond this command

utility---setting---ABAP Editor---Editor--frontend editor(new),---72 byte maximum in old version , 

                                  Pretty print(only permitted in new establish)

                                  permitted only daxie


                                  seperate screen(when u see a required code ,to post it on latter)

 
                                  debug

copy the explained sentences format






t-cd t code display



fuuzoku setting

gui houzoku setting

se38

layout setting

**Comment by lawrencepiao** [comment]
体力真的不行，是那个的错误吗，我今天回答问题老是瞎回答，其实我做笔记了，但没想到要记那么多
